import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Let's Build this</h1>

      {/* Header */}


      {/* Navbar */}


      {/* Result */}

      
    </div>
  );
}
